version: '3.8'

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./server:/var/www/html
    ports:
      - 9000:9000
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=bmdekm2nhnbswmekqrkz-mysql.services.clever-cloud.com
      - DB_PORT=3306
      - DB_DATABASE=bmdekm2nhnbswmekqrkz
      - DB_USERNAME=ugblwrwogzgmllxk
      - DB_PASSWORD=HtH1wq1sRKUIwaVlVDLC
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
